config/routes.rb
Caferails::Application.routes.draw do
  resources :caves

end

app/models/cafe.rb
class Cafe < ActiveRecord::Base
end

app/models/crawl_results.rb
class CrawlResults < ActiveRecord::Base
end

app/models/geocode_results.rb
class GeocodeResults < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/caves_controller.rb
class CavesController < ApplicationController
  before_action :set_cafe, only: [:show, :edit, :update, :destroy]

  # GET /caves
  # GET /caves.json
  def index
    @caves = Cafe.all
  end

  # GET /caves/1
  # GET /caves/1.json
  def show
  end

  # GET /caves/new
  def new
    @cafe = Cafe.new
  end

  # GET /caves/1/edit
  def edit
  end

  # POST /caves
  # POST /caves.json
  def create
    @cafe = Cafe.new(cafe_params)

    respond_to do |format|
      if @cafe.save
        format.html { redirect_to @cafe, notice: 'Cafe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cafe }
      else
        format.html { render action: 'new' }
        format.json { render json: @cafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caves/1
  # PATCH/PUT /caves/1.json
  def update
    respond_to do |format|
      if @cafe.update(cafe_params)
        format.html { redirect_to @cafe, notice: 'Cafe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cafe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caves/1
  # DELETE /caves/1.json
  def destroy
    @cafe.destroy
    respond_to do |format|
      format.html { redirect_to caves_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cafe
      @cafe = Cafe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cafe_params
      params.require(:cafe).permit(:name, :lat, :lon, :url, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caves_helper.rb
module CavesHelper
end

app/views/caves/_form.html.erb
<%= form_for(@cafe) do |f| %>
  <% if @cafe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cafe.errors.count, "error") %> prohibited this cafe from being saved:</h2>

      <ul>
      <% @cafe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/caves/edit.html.erb
<h1>Editing cafe</h1>

<%= render 'form' %>

<%= link_to 'Show', @cafe %> |
<%= link_to 'Back', caves_path %>

app/views/caves/index.html.erb
<h1>Listing caves</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Url</th>
      <th>Address</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @caves.each do |cafe| %>
      <tr>
        <td><%= cafe.name %></td>
        <td><%= cafe.lat %></td>
        <td><%= cafe.lon %></td>
        <td><%= cafe.url %></td>
        <td><%= cafe.address %></td>
        <td><%= link_to 'Show', cafe %></td>
        <td><%= link_to 'Edit', edit_cafe_path(cafe) %></td>
        <td><%= link_to 'Destroy', cafe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cafe', new_cafe_path %>

app/views/caves/new.html.erb
<h1>New cafe</h1>

<%= render 'form' %>

<%= link_to 'Back', caves_path %>

app/views/caves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cafe.name %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @cafe.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @cafe.lon %>
</p>

<p>
  <strong>Url:</strong>
  <%= @cafe.url %>
</p>

<p>
  <strong>Address:</strong>
  <%= @cafe.address %>
</p>

<%= link_to 'Edit', edit_cafe_path(@cafe) %> |
<%= link_to 'Back', caves_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Caferails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>